project_id = "xlhbjkkerfprkiqmlaan"

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.wallet-pay]
verify_jwt = false

[functions.process-refund]
verify_jwt = false
